version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-chi/render.Render)
        - (github.com/go-chi/render.Status)
    gosec:
      excludes:
        - G112
    revive:
      rules:
        - name: exported
          disabled: true
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gosec
          - revive
        path: _test\.go
      - linters:
          - errcheck
        text: Error return value of `render.Render` is not checked
      - linters:
          - errcheck
        text: Error return value of `render.Status` is not checked
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: blank-imports
      - linters:
          - revive
        text: stutters; consider calling this Service
      - linters:
          - revive
        text: stutters; consider calling this Result
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
