run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - revive      # replaces deprecated golint
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused      # replaces deprecated varcheck
    - gosec

linters-settings:
  errcheck:
    # List of functions to exclude from checking
    # render.Render is commonly ignored because it's used for HTTP responses
    # where the error is typically not actionable (client already disconnected, etc.)
    exclude-functions:
      - (github.com/go-chi/render.Render)
      - (github.com/go-chi/render.Status)
  
  gosec:
    # Exclude specific security rules
    excludes:
      - G112  # Potential Slowloris Attack (ReadHeaderTimeout not configured)
  
  revive:
    # Enable only essential rules to avoid noise
    rules:
      - name: exported
        disabled: true  # Allow interface naming patterns like AuthService
      - name: var-naming
        disabled: true  # Allow underscore naming in some cases

issues:
  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
        - revive
    
    # Exclude render.Render error checks specifically
    - text: "Error return value of `render.Render` is not checked"
      linters:
        - errcheck
    
    - text: "Error return value of `render.Status` is not checked"
      linters:
        - errcheck
    
    # Allow unused parameters in interface implementations and handlers
    - text: "unused-parameter"
      linters:
        - revive
    
    # Allow blank imports for database drivers and similar
    - text: "blank-imports"
      linters:
        - revive
    
    # Allow service interface naming patterns (common in Go)
    - text: "stutters; consider calling this Service"
      linters:
        - revive
    
    # Allow result/response type naming patterns
    - text: "stutters; consider calling this Result"
      linters:
        - revive

  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 10